### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by antoniojosesanchez** [GheorgheBci/TheOwl#1]
- Aclarar el esquema E/R: ¿ALQUILA es una relación TERNARIA?

**Comment by GheorgheBci** [comment]
Buenas Antonio, ALQUILA no es una relación Ternaria sino una relación muchos a muchos y DETALLES_ALQUILER es la tabla intermedia entre esas dos relaciones. Ahora en un rato especifico mejor esa relación en el esquema E/R.
